# permissions for end users to view nodectrls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodectrl-viewer-role
rules:
- apiGroups:
  - mygroup.example.com
  resources:
  - nodectrls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mygroup.example.com
  resources:
  - nodectrls/status
  verbs:
  - get
