# permissions for end users to edit nodersrcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodersrc-editor-role
rules:
- apiGroups:
  - mygroup.example.com
  resources:
  - nodersrcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mygroup.example.com
  resources:
  - nodersrcs/status
  verbs:
  - get
