# permissions for end users to edit nodectrls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodectrl-editor-role
rules:
- apiGroups:
  - mygroup.example.com
  resources:
  - nodectrls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mygroup.example.com
  resources:
  - nodectrls/status
  verbs:
  - get
