# permissions for end users to view nodersrcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodersrc-viewer-role
rules:
- apiGroups:
  - mygroup.example.com
  resources:
  - nodersrcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mygroup.example.com
  resources:
  - nodersrcs/status
  verbs:
  - get
